### ISSUE TITLE
RFC 1: Choose Technologies

### ISSUE THREAD

**Issue by toadslop** [tokyo-rust/website#2]
We need to decide what technologies we're going to use. This RFC has been created to let Tokyo Rust community members weigh in on the decision. Before making a suggestion, please review the following items from the project README:

* [Project Goals](https://github.com/tokyo-rust/website?tab=readme-ov-file#goals)
* [Project Constraints](https://github.com/tokyo-rust/website?tab=readme-ov-file#project-constraints)

## Main Options

* Static site generator
* Conventional backend + templates
* Conventional backend + SPA framework
* Other options? (please suggest)

**Comment by a-slavica** [comment]
Since we want to do everything in Rust:
- **Frontend**: [Zola](https://www.getzola.org/) or [Yew](https://yew.rs/)
- **Backend**: A classic combination of Tokio/Axum with Diesel and PostgreSQL.

**Comment by toadslop** [comment]
@a-slavica Thanks for you suggestions!

A few questions:

1. What do you see as the tradeoffs between choosing Zola or Yew? Are there any cases were we might benefit from using both?
2. In your opinion, how does Axum compare to other popular frameworks, such as Actix?
3. A common competitor to Diesel is SeaORM. Have you ever used it and if so, how do you think it compares to Diesel?

**Comment by albertoslavicadev** [comment]
Zola in my opinion is faster to set up and deploy, also Zola in great for SEO. For the second and third question I proposed Axum and Diesel since I'm already familiar with both of them. It's always me but unfortunately I had to create a new Github account for work only :D

**Comment by toadslop** [comment]
Let's take some time to see if others chime in, then when the 2 week deadline comes up let's make a final decision.

As it is, I'm thinking a two-phase approach would probabl be good. Phase 1 one be to use Zola and build an entirely static site rapidly that hits the key information-sharing needs of the site. In Phase 2 we can look at features that need a server and database.

**Comment by toadslop** [comment]
@albertoslavicadev Well, we've come to the end of the period and we've had all the comments we're going to get. I propose we use Zola and put together a quick static website to get started.

**Comment by albertoslavicadev** [comment]
Sure, I can start in 2/3 days.

**Comment by toadslop** [comment]
@albertoslavicadev Some of us from the Rust meetup are getting together for coffee and code tomorrow afternoon in Takadanobaba. Want to join us?
